name: nightly

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'refs/heads/dev'
          fetch-depth: 0 # All history
      - name: fetch tags
        run: git fetch --depth=1 origin "+refs/tags/*:refs/tags/*"
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - name: install
        run: yarn --check-files --frozen-lockfile --non-interactive
      - name: lint
        run: yarn run lint
      - name: test
        run: yarn test
      - name: build
        run: PACKAGE_SUFFIX=edge yarn build

